/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedBattleRouteImport } from './routes/_authenticated/battle'
import { Route as Authenticated403RouteImport } from './routes/_authenticated/403'
import { Route as AuthenticatedReplayIdRouteImport } from './routes/_authenticated/replay.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBattleRoute = AuthenticatedBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Authenticated403Route = Authenticated403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReplayIdRoute = AuthenticatedReplayIdRouteImport.update({
  id: '/replay/$id',
  path: '/replay/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/403': typeof Authenticated403Route
  '/battle': typeof AuthenticatedBattleRoute
  '/create': typeof AuthenticatedCreateRoute
  '/play': typeof AuthenticatedPlayRoute
  '/replay/$id': typeof AuthenticatedReplayIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/403': typeof Authenticated403Route
  '/battle': typeof AuthenticatedBattleRoute
  '/create': typeof AuthenticatedCreateRoute
  '/play': typeof AuthenticatedPlayRoute
  '/': typeof AuthenticatedIndexRoute
  '/replay/$id': typeof AuthenticatedReplayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/403': typeof Authenticated403Route
  '/_authenticated/battle': typeof AuthenticatedBattleRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/replay/$id': typeof AuthenticatedReplayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/403'
    | '/battle'
    | '/create'
    | '/play'
    | '/replay/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/403' | '/battle' | '/create' | '/play' | '/' | '/replay/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/403'
    | '/_authenticated/battle'
    | '/_authenticated/create'
    | '/_authenticated/play'
    | '/_authenticated/'
    | '/_authenticated/replay/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/battle': {
      id: '/_authenticated/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AuthenticatedBattleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/403': {
      id: '/_authenticated/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Authenticated403RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/replay/$id': {
      id: '/_authenticated/replay/$id'
      path: '/replay/$id'
      fullPath: '/replay/$id'
      preLoaderRoute: typeof AuthenticatedReplayIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  Authenticated403Route: typeof Authenticated403Route
  AuthenticatedBattleRoute: typeof AuthenticatedBattleRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedReplayIdRoute: typeof AuthenticatedReplayIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  Authenticated403Route: Authenticated403Route,
  AuthenticatedBattleRoute: AuthenticatedBattleRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedReplayIdRoute: AuthenticatedReplayIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
