import { vi } from "vitest";
import type { GroupedCreatePageState } from "~/components/create/create-page-state-types";
import type { CreatePageState } from "~/components/create/use-create-page-state";

type MockCreatePageState = CreatePageState & GroupedCreatePageState;

export function createMockPageState(
  overrides: Partial<MockCreatePageState> = {},
): MockCreatePageState {
  const state: CreatePageState = {
    activeTab: "Scenarios",
    linkageFilter: { mode: "all" },
    scenarioFilterOptions: [
      { id: "sc-1", name: "Ambush at Dawn" },
      { id: "sc-2", name: "Castle Siege" },
    ],
    perTabSelection: {
      Effects: null,
      Spells: null,
      Items: null,
      Units: null,
      Scenarios: "sc-1",
    },
    listLoading: {
      Effects: false,
      Spells: false,
      Items: false,
      Units: false,
      Scenarios: false,
    },
    listFetching: {
      Effects: false,
      Spells: false,
      Items: false,
      Units: false,
      Scenarios: false,
    },
    setActiveTab: vi.fn(),
    setLinkageFilter: vi.fn(),
    selectRecord: vi.fn(),
    createNew: vi.fn(),
    scenarioListItems: [
      {
        id: "sc-1",
        name: "Ambush at Dawn",
        updatedAt: new Date("2025-06-10T00:00:00Z"),
        createdAt: new Date("2025-05-01T00:00:00Z"),
      },
    ],
    scenarioPage: 1,
    scenarioTotalPages: 1,
    scenarioSortBy: "name",
    scenarioSortDir: "asc",
    setScenarioPage: vi.fn(),
    setScenarioSort: vi.fn(),
    requestDeleteScenario: vi.fn(),
    effectListItems: [],
    effectPage: 1,
    effectTotalPages: 1,
    effectSortBy: "name",
    effectSortDir: "asc",
    setEffectPage: vi.fn(),
    setEffectSort: vi.fn(),
    requestDeleteEffect: vi.fn(),
    spellListItems: [],
    spellPage: 1,
    spellTotalPages: 1,
    spellSortBy: "name",
    spellSortDir: "asc",
    setSpellPage: vi.fn(),
    setSpellSort: vi.fn(),
    requestDeleteSpell: vi.fn(),
    itemListItems: [],
    itemPage: 1,
    itemTotalPages: 1,
    itemSortBy: "name",
    itemSortDir: "asc",
    setItemPage: vi.fn(),
    setItemSort: vi.fn(),
    requestDeleteItem: vi.fn(),
    unitListItems: [],
    unitPage: 1,
    unitTotalPages: 1,
    unitSortBy: "name",
    unitSortDir: "asc",
    setUnitPage: vi.fn(),
    setUnitSort: vi.fn(),
    requestDeleteUnit: vi.fn(),
    scenarioWorkspace: {
      mode: "idle",
      entityType: null,
      entityId: null,
      data: null,
      formValues: {},
      isDirty: false,
    },
    updateScenarioField: vi.fn(),
    saveScenario: vi.fn(),
    isScenarioSaving: false,
    scenarioSaveError: null,
    scenarioUnitOptions: [],
    entityWorkspace: {
      mode: "idle",
      entityType: null,
      entityId: null,
      data: null,
      formValues: {},
      isDirty: false,
    },
    updateEntityField: vi.fn(),
    saveEntity: vi.fn(),
    isEntitySaving: false,
    entitySaveError: null,
    effectOptions: [],
    spellOptions: [],
    itemOptions: [],
    isDialogOpen: true,
    pendingAction: null,
    cancelDiscard: vi.fn(),
    confirmDiscard: vi.fn(),
    isDeleteDialogOpen: true,
    deleteTarget: { id: "sc-1", name: "Ambush at Dawn" },
    deleteError: "scenario delete error",
    cancelDeleteScenario: vi.fn(),
    confirmDeleteScenario: vi.fn(),
    isDeleteEffectDialogOpen: true,
    deleteEffectTarget: { id: "ef-1", name: "Arcane Damage" },
    deleteEffectError: "effect delete error",
    cancelDeleteEffect: vi.fn(),
    confirmDeleteEffect: vi.fn(),
    isDeleteSpellDialogOpen: true,
    deleteSpellTarget: { id: "sp-1", name: "Battle Cry" },
    deleteSpellError: "spell delete error",
    cancelDeleteSpell: vi.fn(),
    confirmDeleteSpell: vi.fn(),
    isDeleteItemDialogOpen: true,
    deleteItemTarget: { id: "it-1", name: "Iron Sword" },
    deleteItemError: "item delete error",
    cancelDeleteItem: vi.fn(),
    confirmDeleteItem: vi.fn(),
    isDeleteUnitDialogOpen: true,
    deleteUnitTarget: { id: "un-1", name: "Barbarian" },
    deleteUnitError: "unit delete error",
    cancelDeleteUnit: vi.fn(),
    confirmDeleteUnit: vi.fn(),
    ...overrides,
  };

  const groupedState = Object.assign(state, {
    workspaces: {
      entity: state.entityWorkspace,
      scenario: state.scenarioWorkspace,
      updateEntityField: state.updateEntityField,
      updateScenarioField: state.updateScenarioField,
    },
    domains: {
      scenarios: {
        list: {
          items: state.scenarioListItems,
          page: state.scenarioPage,
          totalPages: state.scenarioTotalPages,
          sortBy: state.scenarioSortBy,
          sortDir: state.scenarioSortDir,
          setPage: state.setScenarioPage,
          setSort: state.setScenarioSort,
        },
        deletion: {
          isOpen: state.isDeleteDialogOpen,
          target: state.deleteTarget,
          error: state.deleteError,
          request: state.requestDeleteScenario,
          confirm: state.confirmDeleteScenario,
          cancel: state.cancelDeleteScenario,
        },
      },
      effects: {
        list: {
          items: state.effectListItems,
          page: state.effectPage,
          totalPages: state.effectTotalPages,
          sortBy: state.effectSortBy,
          sortDir: state.effectSortDir,
          setPage: state.setEffectPage,
          setSort: state.setEffectSort,
        },
        deletion: {
          isOpen: state.isDeleteEffectDialogOpen,
          target: state.deleteEffectTarget,
          error: state.deleteEffectError,
          request: state.requestDeleteEffect,
          confirm: state.confirmDeleteEffect,
          cancel: state.cancelDeleteEffect,
        },
      },
      spells: {
        list: {
          items: state.spellListItems,
          page: state.spellPage,
          totalPages: state.spellTotalPages,
          sortBy: state.spellSortBy,
          sortDir: state.spellSortDir,
          setPage: state.setSpellPage,
          setSort: state.setSpellSort,
        },
        deletion: {
          isOpen: state.isDeleteSpellDialogOpen,
          target: state.deleteSpellTarget,
          error: state.deleteSpellError,
          request: state.requestDeleteSpell,
          confirm: state.confirmDeleteSpell,
          cancel: state.cancelDeleteSpell,
        },
      },
      items: {
        list: {
          items: state.itemListItems,
          page: state.itemPage,
          totalPages: state.itemTotalPages,
          sortBy: state.itemSortBy,
          sortDir: state.itemSortDir,
          setPage: state.setItemPage,
          setSort: state.setItemSort,
        },
        deletion: {
          isOpen: state.isDeleteItemDialogOpen,
          target: state.deleteItemTarget,
          error: state.deleteItemError,
          request: state.requestDeleteItem,
          confirm: state.confirmDeleteItem,
          cancel: state.cancelDeleteItem,
        },
      },
      units: {
        list: {
          items: state.unitListItems,
          page: state.unitPage,
          totalPages: state.unitTotalPages,
          sortBy: state.unitSortBy,
          sortDir: state.unitSortDir,
          setPage: state.setUnitPage,
          setSort: state.setUnitSort,
        },
        deletion: {
          isOpen: state.isDeleteUnitDialogOpen,
          target: state.deleteUnitTarget,
          error: state.deleteUnitError,
          request: state.requestDeleteUnit,
          confirm: state.confirmDeleteUnit,
          cancel: state.cancelDeleteUnit,
        },
      },
    },
    navigation: {
      perTabSelection: state.perTabSelection,
      selectRecord: state.selectRecord,
      createNew: state.createNew,
      discard: {
        isOpen: state.isDialogOpen,
        confirm: state.confirmDiscard,
        cancel: state.cancelDiscard,
      },
    },
    entitySave: {
      save: state.saveEntity,
      isSaving: state.isEntitySaving,
      error: state.entitySaveError,
    },
    scenarioSave: {
      save: state.saveScenario,
      isSaving: state.isScenarioSaving,
      error: state.scenarioSaveError,
    },
    options: {
      effects: state.effectOptions,
      spells: state.spellOptions,
      items: state.itemOptions,
      scenarioUnits: state.scenarioUnitOptions,
      scenarioFilters: state.scenarioFilterOptions,
    },
  });

  return Object.assign(groupedState, overrides);
}
