import { vi } from "vitest";
import type { CreatePageState } from "~/components/create/use-create-page-state";

export function createMockPageState(overrides: Partial<CreatePageState> = {}): CreatePageState {
  return {
    activeTab: "Scenarios",
    perTabSelection: {
      Effects: null,
      Spells: null,
      Items: null,
      Units: null,
      Scenarios: "sc-1",
    },
    listLoading: {
      Effects: false,
      Spells: false,
      Items: false,
      Units: false,
      Scenarios: false,
    },
    listFetching: {
      Effects: false,
      Spells: false,
      Items: false,
      Units: false,
      Scenarios: false,
    },
    setActiveTab: vi.fn(),
    selectRecord: vi.fn(),
    createNew: vi.fn(),
    scenarioListItems: [
      {
        id: "sc-1",
        name: "Ambush at Dawn",
        updatedAt: new Date("2025-06-10T00:00:00Z"),
        createdAt: new Date("2025-05-01T00:00:00Z"),
      },
    ],
    scenarioPage: 1,
    scenarioTotalPages: 1,
    scenarioSortBy: "name",
    scenarioSortDir: "asc",
    setScenarioPage: vi.fn(),
    setScenarioSort: vi.fn(),
    requestDeleteScenario: vi.fn(),
    effectListItems: [],
    effectPage: 1,
    effectTotalPages: 1,
    effectSortBy: "name",
    effectSortDir: "asc",
    setEffectPage: vi.fn(),
    setEffectSort: vi.fn(),
    requestDeleteEffect: vi.fn(),
    spellListItems: [],
    spellPage: 1,
    spellTotalPages: 1,
    spellSortBy: "name",
    spellSortDir: "asc",
    setSpellPage: vi.fn(),
    setSpellSort: vi.fn(),
    requestDeleteSpell: vi.fn(),
    itemListItems: [],
    itemPage: 1,
    itemTotalPages: 1,
    itemSortBy: "name",
    itemSortDir: "asc",
    setItemPage: vi.fn(),
    setItemSort: vi.fn(),
    requestDeleteItem: vi.fn(),
    unitListItems: [],
    unitPage: 1,
    unitTotalPages: 1,
    unitSortBy: "name",
    unitSortDir: "asc",
    setUnitPage: vi.fn(),
    setUnitSort: vi.fn(),
    requestDeleteUnit: vi.fn(),
    scenarioWorkspace: {
      mode: "idle",
      entityType: null,
      entityId: null,
      data: null,
      formValues: {},
      isDirty: false,
    },
    updateScenarioField: vi.fn(),
    saveScenario: vi.fn(),
    isScenarioSaving: false,
    scenarioSaveError: null,
    scenarioUnitOptions: [],
    entityWorkspace: {
      mode: "idle",
      entityType: null,
      entityId: null,
      data: null,
      formValues: {},
      isDirty: false,
    },
    updateEntityField: vi.fn(),
    saveEntity: vi.fn(),
    isEntitySaving: false,
    entitySaveError: null,
    effectOptions: [],
    spellOptions: [],
    itemOptions: [],
    isDialogOpen: true,
    pendingAction: null,
    cancelDiscard: vi.fn(),
    confirmDiscard: vi.fn(),
    isDeleteDialogOpen: true,
    deleteTarget: { id: "sc-1", name: "Ambush at Dawn" },
    deleteError: "scenario delete error",
    cancelDeleteScenario: vi.fn(),
    confirmDeleteScenario: vi.fn(),
    isDeleteEffectDialogOpen: true,
    deleteEffectTarget: { id: "ef-1", name: "Arcane Damage" },
    deleteEffectError: "effect delete error",
    cancelDeleteEffect: vi.fn(),
    confirmDeleteEffect: vi.fn(),
    isDeleteSpellDialogOpen: true,
    deleteSpellTarget: { id: "sp-1", name: "Battle Cry" },
    deleteSpellError: "spell delete error",
    cancelDeleteSpell: vi.fn(),
    confirmDeleteSpell: vi.fn(),
    isDeleteItemDialogOpen: true,
    deleteItemTarget: { id: "it-1", name: "Iron Sword" },
    deleteItemError: "item delete error",
    cancelDeleteItem: vi.fn(),
    confirmDeleteItem: vi.fn(),
    isDeleteUnitDialogOpen: true,
    deleteUnitTarget: { id: "un-1", name: "Barbarian" },
    deleteUnitError: "unit delete error",
    cancelDeleteUnit: vi.fn(),
    confirmDeleteUnit: vi.fn(),
    ...overrides,
  };
}
